### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by leventepvp** [acscripts/ac_gifts#2]
### Version

V1.0.1

### Framework

es_extended

### Issue description

![image](https://user-images.githubusercontent.com/59410749/208481661-a6b45baa-4d4d-4ef5-9c1f-3e414e608145.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/59410749/208481671-919833ec-f441-41ec-bcb7-479449f98ebc.png)

### Confirm the following statements:

- [X] This issue is not a question or a feature request.
- [x] I have provided a **detailed** issue description and **detailed** reproduction steps.

**Comment by leventepvp** [comment]
![image](https://user-images.githubusercontent.com/59410749/208482017-3d35b021-2024-41ab-a329-7a744cbc4b96.png)

**Comment by antond15** [comment]
Start `ox_inventory` before `ac_gifts` **or** download the latest release of `ox_inventory`.
